/* Does specialising the fragment shader on the combiner program change a
 * single pixel?
 *
 * nv2a_metal.m's shade() interprets the NV2A register combiners per pixel.
 * RECOMP_METAL_SPECIALISE_COMBINERS (default on) instead bakes the combiner
 * words into the pipeline as Metal function constants, so the compiler
 * resolves every input and output switch and unrolls the stage loop. That is
 * a claim of EXACTNESS, not of closeness: the specialised shader must compute
 * the same float operations in the same order. So the gate is byte equality.
 *
 * This renders a spread of combiner programs and writes every target to a
 * dump; metal_combiner_spec_check.sh runs it with the switch off and on and
 * requires the two dumps to be BYTE-IDENTICAL, and runs a third arm with
 * RECOMP_METAL_SPECIALISE_COMBINERS_CONTROL=1 -- which specialises on
 * deliberately wrong words -- that must DIFFER, or the scene cannot see a
 * wrong specialisation at all.
 *
 * The programs:
 *   - realistic D3D fixed-function setups, generated by the transcription of
 *     the title's own stage-state -> combiner builder (d3d8_ff_combiner.c):
 *     MODULATE, SELECTARG1/2, a two-stage chain, alpha ops, DOT3, a disabled
 *     stage, LERP/MULTIPLYADD, TFACTOR and a four-stage four-texture chain;
 *   - the combiner-free tails (untextured, texture, texture*diffuse);
 *   - arbitrary word sets from a fixed LCG, which reach the mux, the dot
 *     products, the blue-to-alpha bits, every mapping and every destination.
 * Each case is drawn twice: once opaque over the whole target, once
 * source-alpha blended over part of it, so the alpha chain reaches pixels.
 *
 * `vsh` as the second argument draws every case through a guest vertex
 * program on the GPU instead of the fixed `vs` -- the player's configuration
 * (RECOMP_METAL_VSH defaults on), whose pipelines come out of the program's
 * own library and a separate cache. The program is MOVs from the inputs the
 * fixed path reads, so both vertex paths draw the same geometry.
 *
 * `bench` as the second argument instead times a synthetic full-screen
 * 640x480 workload (see bench()), for the generic-vs-specialised GPU cost.
 *
 * `twice` as the third argument (or the second, for the fixed `vs`) renders the
 * whole case list twice in one process, both passes into the dump, with
 * nv2a_metal_pipelines_settle() between them. Under RECOMP_METAL_ASYNC_PIPELINES
 * with RECOMP_METAL_PIPELINE_HOLD every pass-1 draw finds its specialised
 * pipeline still compiling and takes the generic one, and every pass-2 draw
 * takes the specialised one -- so a dump equal to the generic arm's says the
 * fallback on a miss and the pipeline swapped in afterwards both render the
 * same pixels. metal_pipeline_archive_check.sh uses the same binary to show a
 * second process loading its pipelines from the archive instead of compiling.
 * Needs a real GPU.
 */
#include "nv2a_metal.h"
#include "nv2a_texture_copy.h"
#include "d3d8_ff_combiner.h"
#include "vsh_encode.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define W 128u
#define H 128u
#define TW 32u
static uint8_t target[W*H*2], depth[W*H*4];
static uint8_t tex[4][TW*TW*4];

static unsigned rng = 0x5eed1234u;
static unsigned rnd(void) { rng = rng * 1103515245u + 12345u; return rng >> 7; }

static unsigned morton(unsigned x, unsigned y)
{ unsigned i = 0, bit = 0; for (unsigned b = 1; b < TW; b <<= 1) { if (x & b) i |= 1u << bit; ++bit; if (y & b) i |= 1u << bit; ++bit; } return i; }

static void make_textures(void)
{
    for (unsigned t = 0; t < 4; ++t)
        for (unsigned y = 0; y < TW; ++y)
            for (unsigned x = 0; x < TW; ++x) {
                uint8_t *c = tex[t] + 4 * morton(x, y);          /* BGRA */
                c[0] = (uint8_t)(x * 8 + t * 40);
                c[1] = (uint8_t)(y * 8 ^ (t * 0x35));
                c[2] = (uint8_t)((x + y) * 4 + t * 17);
                c[3] = (uint8_t)(((x / 4 + y / 4 + t) & 1) ? 255 - x * 3 : y * 7);
            }
}

typedef struct {
    const char *name;
    uint32_t cc, ci[8], ai[8], co[8], ao[8], k0[8], k1[8];
    uint32_t tmask, add_specular, untextured, modulate;
    uint32_t fcw0, fcw1, fog_mode;   /* G53: a final-combiner program other than the two fog-off ones */
} Case;

#define MAXCASES 48
static Case cases[MAXCASES];
static unsigned ncases;

/* D3D8 stage-state helpers, as d3d8_ff_combiner_test.c spells them. */
enum { DIF = D3D8FF_TA_DIFFUSE, CUR = D3D8FF_TA_CURRENT, TEX = D3D8FF_TA_TEXTURE,
       TFC = D3D8FF_TA_TFACTOR, SPC = D3D8FF_TA_SPECULAR, CMP = D3D8FF_TA_COMPLEMENT,
       ARP = D3D8FF_TA_ALPHAREPLICATE };
static void ffinit(D3D8FFCombinerIn *in)
{
    memset(in, 0, sizeof *in);
    for (int s = 0; s < 4; ++s) {
        in->tss[s][D3D8FF_TSS_COLOROP] = D3D8FF_TOP_DISABLE;
        in->tss[s][D3D8FF_TSS_ALPHAOP] = D3D8FF_TOP_DISABLE;
        in->tss[s][D3D8FF_TSS_RESULTARG] = CUR;
    }
}
static void ffstage(D3D8FFCombinerIn *in, int s, uint32_t cop, uint32_t c0, uint32_t c1, uint32_t c2,
                    uint32_t aop, uint32_t a0, uint32_t a1, uint32_t a2)
{
    in->tss[s][D3D8FF_TSS_COLOROP] = cop; in->tss[s][D3D8FF_TSS_COLORARG0] = c0;
    in->tss[s][D3D8FF_TSS_COLORARG1] = c1; in->tss[s][D3D8FF_TSS_COLORARG2] = c2;
    in->tss[s][D3D8FF_TSS_ALPHAOP] = aop; in->tss[s][D3D8FF_TSS_ALPHAARG0] = a0;
    in->tss[s][D3D8FF_TSS_ALPHAARG1] = a1; in->tss[s][D3D8FF_TSS_ALPHAARG2] = a2;
    in->tss[s][D3D8FF_TSS_RESULTARG] = CUR;
}
static Case *add_ff(const char *name, const D3D8FFCombinerIn *in, uint32_t tfactor)
{
    D3D8FFCombiners o; Case *c = &cases[ncases];
    if (d3d8_ff_combiners(in, &o) != 0 || !o.emitted) {
        fprintf(stderr, "FAIL: d3d8_ff_combiners refused case %s\n", name); exit(1);
    }
    memset(c, 0, sizeof *c);
    c->name = name; c->cc = o.combiner_control & 0xFu;
    memcpy(c->ci, o.color_icw, sizeof c->ci); memcpy(c->ai, o.alpha_icw, sizeof c->ai);
    memcpy(c->co, o.color_ocw, sizeof c->co); memcpy(c->ao, o.alpha_ocw, sizeof c->ao);
    for (int i = 0; i < 8; ++i) c->k0[i] = c->k1[i] = tfactor;
    c->tmask = in->texture_bound_mask;
    ++ncases; return c;
}

static void build_cases(void)
{
    D3D8FFCombinerIn in;
    enum { DIS = D3D8FF_TOP_DISABLE, SEL1 = D3D8FF_TOP_SELECTARG1, SEL2 = D3D8FF_TOP_SELECTARG2,
           MOD = D3D8FF_TOP_MODULATE, MOD2X = D3D8FF_TOP_MODULATE2X, MOD4X = D3D8FF_TOP_MODULATE4X,
           ADD = D3D8FF_TOP_ADD, ADDS = D3D8FF_TOP_ADDSIGNED, ADDS2X = D3D8FF_TOP_ADDSIGNED2X,
           SUB = D3D8FF_TOP_SUBTRACT, BTA = D3D8FF_TOP_BLENDTEXTUREALPHA,
           BDA = D3D8FF_TOP_BLENDDIFFUSEALPHA, DOT3 = D3D8FF_TOP_DOTPRODUCT3,
           MAD = D3D8FF_TOP_MULTIPLYADD, LERP = D3D8FF_TOP_LERP,
           MAAC = D3D8FF_TOP_MODULATEALPHA_ADDCOLOR, ADDSM = D3D8FF_TOP_ADDSMOOTH };

    ffinit(&in); ffstage(&in, 0, MOD, CUR, TEX, DIF, MOD, CUR, TEX, DIF);
    in.texture_bound_mask = 1; add_ff("ff MODULATE tex*diffuse", &in, 0);

    ffinit(&in); ffstage(&in, 0, SEL1, CUR, TEX, DIF, SEL2, CUR, TEX, DIF);
    in.texture_bound_mask = 1; add_ff("ff SELECTARG1 tex / SELECTARG2 diffuse", &in, 0);

    ffinit(&in); ffstage(&in, 0, MOD, CUR, TEX, DIF, MOD, CUR, TEX, DIF);
    ffstage(&in, 1, MOD2X, CUR, TEX, CUR, DIS, CUR, TEX, CUR);
    in.texture_bound_mask = 3; add_ff("ff two-stage MOD then MOD2X", &in, 0);

    ffinit(&in); ffstage(&in, 0, SEL1, CUR, DIF, TEX, MOD, CUR, TEX, DIF);
    ffstage(&in, 1, BTA, CUR, TEX, CUR, SUB, CUR, TEX, CUR);
    in.texture_bound_mask = 3; add_ff("ff alpha ops BLENDTEXTUREALPHA/SUBTRACT", &in, 0);

    ffinit(&in); ffstage(&in, 0, DOT3, CUR, TEX, DIF, SEL1, CUR, DIF, TEX);
    in.texture_bound_mask = 1; add_ff("ff DOT3 tex.diffuse", &in, 0);

    ffinit(&in); ffstage(&in, 0, DIS, CUR, TEX, DIF, SEL1, CUR, TEX, DIF);
    in.texture_bound_mask = 1; add_ff("ff disabled stage 0", &in, 0);

    ffinit(&in); ffstage(&in, 0, MOD, CUR, TEX, DIF, MOD, CUR, TEX, DIF);
    ffstage(&in, 1, DIS, CUR, TEX, CUR, DIS, CUR, TEX, CUR);
    in.texture_bound_mask = 3; add_ff("ff MOD then disabled stage 1", &in, 0);

    ffinit(&in); ffstage(&in, 0, ADDS2X, CUR, TEX, DIF, ADDS, CUR, TEX, DIF);
    ffstage(&in, 1, MOD4X, CUR, TEX, CUR, ADD, CUR, TEX, CUR);
    in.texture_bound_mask = 3; add_ff("ff ADDSIGNED2X then MOD4X", &in, 0);

    ffinit(&in); ffstage(&in, 0, LERP, TEX | ARP, TEX, DIF, MAD, DIF, TEX, DIF);
    in.texture_bound_mask = 1; add_ff("ff LERP / MULTIPLYADD", &in, 0);

    ffinit(&in); ffstage(&in, 0, MOD, CUR, TEX, TFC, MOD, CUR, TFC, DIF | CMP);
    in.texture_bound_mask = 1; add_ff("ff TFACTOR and complement", &in, 0x80FF4020u);

    ffinit(&in); ffstage(&in, 0, MOD, CUR, TEX, DIF, SEL1, CUR, TEX, DIF);
    ffstage(&in, 1, BDA, CUR, TEX, CUR, MOD, CUR, TEX, CUR);
    ffstage(&in, 2, MAAC, CUR, CUR, TEX, SEL1, CUR, TEX, CUR);
    ffstage(&in, 3, ADDSM, CUR, TEX, SPC, MOD2X, CUR, TEX, CUR);
    in.texture_bound_mask = 15; add_ff("ff four stages four textures", &in, 0x40808080u);

    ffinit(&in); ffstage(&in, 0, MOD, CUR, TEX, DIF, MOD, CUR, TEX, DIF);
    in.texture_bound_mask = 1; add_ff("ff MODULATE + add_specular", &in, 0)->add_specular = 1;

    /* The combiner-free tails: shade()'s cc == 0 branch. */
    { Case *c = &cases[ncases++]; memset(c, 0, sizeof *c); c->name = "no combiner: untextured"; c->untextured = 1; }
    { Case *c = &cases[ncases++]; memset(c, 0, sizeof *c); c->name = "no combiner: texture"; c->tmask = 1; }
    { Case *c = &cases[ncases++]; memset(c, 0, sizeof *c); c->name = "no combiner: texture*diffuse"; c->tmask = 1; c->modulate = 1; }

    /* G53: the final combiner, specialised on its two words. D3D's fog
     * programs over a MODULATE stage, in LINEAR and EXP2, and two arbitrary
     * programs that reach EF_PROD, V1R0_SUM, both complements and C0/C1. */
    {   static const struct { const char *name; uint32_t w0, w1, mode; } fc[] = {
            { "final: D3D fog LINEAR", 0x130C0300u, 0x1C80u, 0x2601 },
            { "final: D3D fog + specular EXP2", 0x130E0300u, 0x1C80u, 0x801 },
            { "final: arbitrary EF/V1R0/C0", 0x0F2E0103u, 0x0405ACE0u, 0x2601 },
            { "final: arbitrary inverted", 0x33250E24u, 0x0C231B40u, 0x800 } };
        for (unsigned f = 0; f < 4; ++f) {
            ffinit(&in); ffstage(&in, 0, MOD, CUR, TEX, DIF, MOD, CUR, TEX, DIF);
            in.texture_bound_mask = 1;
            Case *c = add_ff(fc[f].name, &in, 0);
            c->fcw0 = fc[f].w0; c->fcw1 = fc[f].w1; c->fog_mode = fc[f].mode;
        }
    }

    /* Arbitrary words. Inputs are masked to valid register numbers so the
     * programs read defined registers (1..5, 8..13) but every mapping, the
     * alpha-replicate bit, the dot products, the mux, blue-to-alpha and all
     * destinations stay random. */
    static const char *arb_names[] = { "arbitrary 1", "arbitrary 2", "arbitrary 3", "arbitrary 4",
                                       "arbitrary 5", "arbitrary 6", "arbitrary 7", "arbitrary 8",
                                       "arbitrary 9", "arbitrary 10", "arbitrary 11", "arbitrary 12" };
    static const uint32_t regs[] = { 0, 1, 2, 4, 5, 8, 9, 10, 11, 12, 13 };
    for (unsigned a = 0; a < 12; ++a) {
        Case *c = &cases[ncases++]; memset(c, 0, sizeof *c);
        c->name = arb_names[a]; c->cc = 1 + a % 8; c->tmask = rnd() & 15; c->add_specular = rnd() & 1;
        for (unsigned s = 0; s < c->cc; ++s) {
            uint32_t ci = 0, ai = 0;
            for (int k = 0; k < 4; ++k) {
                uint32_t code = (rnd() & 0xE0u) | (rnd() & 0x10u) | regs[rnd() % 11];
                uint32_t acode = (rnd() & 0xE0u) | (rnd() & 0x10u) | regs[rnd() % 11];
                ci = (ci << 8) | code; ai = (ai << 8) | acode;
            }
            c->ci[s] = ci; c->ai[s] = ai;
            c->co[s] = rnd() & 0x000FFFFFu;          /* dest, dot, mux, mapping, blue->alpha */
            c->ao[s] = rnd() & 0x0003FFFFu;
            c->k0[s] = rnd() * 2654435761u; c->k1[s] = rnd() * 40503u;
        }
        /* The result is R0 (register 12). Random destinations rarely leave
         * anything there, which draws the same flat picture for most
         * programs and tests nothing -- so the last stage's sum always
         * lands in R0, colour and alpha. */
        c->co[c->cc - 1] = (c->co[c->cc - 1] & ~0x00000F00u) | 0x00000C00u;
        c->ao[c->cc - 1] = (c->ao[c->cc - 1] & ~0x00000F00u) | 0x00000C00u;
    }
}

static NV2ATextureCopy extra[3];

/* MOV oPos,v0; MOV oD0,v3; MOV oD1,v4; MOV oT0..oT3,v9..v12; MOV oFog,v5. */
static int use_vsh;
static uint32_t vsh_words[8][4];
static float vsh_consts[192][4];
static void build_vsh(void)
{
    static const unsigned in[8]  = { 0, 3, 4, 9, 10, 11, 12, 5 };
    static const unsigned out[8] = { 0, 3, 4, 9, 10, 11, 12, 5 };
    for (int i = 0; i < 8; ++i) {
        VshIns x; memset(&x, 0, sizeof x);
        x.mac = 1; x.input_index = in[i];                 /* NV2A_VSH_MAC_MOV */
        x.a.mux = 2; x.a.swz = SWZ_ID; x.b.mux = 2; x.b.swz = SWZ_ID; x.c.mux = 2; x.c.swz = SWZ_ID;
        x.out_mask = out[i] == 5 ? 0x8 : 0xF; x.out_reg = out[i]; x.final = i == 7;
        vsh_encode(vsh_words[i], &x);
    }
}

static void setup(NV2ATextureCopy *s, const Case *c, unsigned w, unsigned h)
{
    memset(s, 0, sizeof *s);
    s->width = s->height = TW; s->pitch = TW * 4; s->levels = 1; s->rgba8 = 1;
    s->min_filter = 2; s->linear = 1; s->repeat = 1;
    s->clip_w = w; s->clip_h = h; s->target_pitch = w * 2; s->target_bpp = 2; s->depth_pitch = w * 4;
    s->z_clip_min = 0.0f; s->z_clip_max = 16777215.0f;
    s->combiner_count = c->cc; s->texture_mask = c->tmask;
    s->add_specular = c->add_specular; s->untextured = c->untextured; s->modulate = c->modulate;
    memcpy(s->color_icw, c->ci, sizeof c->ci); memcpy(s->alpha_icw, c->ai, sizeof c->ai);
    memcpy(s->color_ocw, c->co, sizeof c->co); memcpy(s->alpha_ocw, c->ao, sizeof c->ao);
    memcpy(s->const0, c->k0, sizeof c->k0); memcpy(s->const1, c->k1, sizeof c->k1);
    if (c->fcw0 || c->fcw1) {
        s->final_general = 1; s->final_cw0 = c->fcw0; s->final_cw1 = c->fcw1; s->add_specular = 0;
        s->fog_enable = 1; s->fog_mode = c->fog_mode; s->fog_color = 0x00306090u;
        s->fog_p0 = c->fog_mode == 0x2601 ? 1.5f : 1.5f; s->fog_p1 = c->fog_mode == 0x2601 ? -0.004f : -0.02f;
        s->spec_fog_c0 = 0x80C04020u; s->spec_fog_c1 = 0x20406080u;
    }
    for (unsigned u = 0; u < 3; ++u) {
        extra[u] = *s; extra[u].min_filter = u == 1 ? 1 : 2; extra[u].linear = u != 1;
        s->extra_texture[u] = tex[u + 1]; s->extra_size[u] = sizeof tex[u + 1];
    }
    s->extra_stages = extra;
}

/* A quad from (x0,y0) to (x1,y1), with colours and coordinates that vary over
 * it: every combiner input is a gradient, including specular. */
static void quad(float v[6][16][4], float x0, float y0, float x1, float y1, unsigned seed)
{
    const float P[6][2] = {{0,0},{1,0},{1,1},{0,0},{1,1},{0,1}};
    memset(v, 0, sizeof(float) * 6 * 16 * 4);
    for (int j = 0; j < 6; ++j) {
        float u = P[j][0], t = P[j][1];
        v[j][0][0] = x0 + (x1 - x0) * u; v[j][0][1] = y0 + (y1 - y0) * t;
        v[j][0][2] = 0.5f * 16777215.0f; v[j][0][3] = 1.0f;
        v[j][3][0] = u; v[j][3][1] = t; v[j][3][2] = 1.0f - u * t; v[j][3][3] = 0.25f + 0.75f * t;
        v[j][4][0] = 0.5f * t; v[j][4][1] = u * 0.8f; v[j][4][2] = (float)(seed % 7) / 7.0f; v[j][4][3] = u;
        v[j][5][0] = 300.0f * u - 20.0f * t;          /* G53: a fog coordinate across the quad */
        for (int k = 0; k < 4; ++k) {
            v[j][9 + k][0] = u * (1.5f + k); v[j][9 + k][1] = t * (2.0f - 0.25f * k);
            v[j][9 + k][3] = 1.0f;
        }
    }
}

static int draw(NV2ATextureCopy *s, uint8_t *tgt, size_t tsize, uint8_t *dep, size_t dsize,
                float x0, float y0, float x1, float y1, unsigned seed)
{
    float v[6][16][4];
    quad(v, x0, y0, x1, y1, seed);
    if (use_vsh) {
        const uint16_t in = (1u << 0) | (1u << 3) | (1u << 4) | (1u << 5) | (15u << 9);
        /* A program whose library is compiling in the background
         * (RECOMP_METAL_ASYNC_VSH) is refused until it is published; the game
         * draws that batch on the CPU. This test is about the fragment stage,
         * so it waits for the program instead. */
        if (!nv2a_metal_vsh_ready((const uint32_t (*)[4])vsh_words, 8, in)) {
            nv2a_metal_pipelines_settle();
            if (!nv2a_metal_vsh_ready((const uint32_t (*)[4])vsh_words, 8, in)) {
                fprintf(stderr, "FAIL: vertex program refused\n"); return 0;
            }
        }
        nv2a_metal_vsh_constants((const float (*)[4])vsh_consts);
    }
    if (nv2a_metal_draw(s, tex[0], sizeof tex[0], tgt, tsize, dep, dsize,
                        (const float (*)[16][4])v, 6, 5) < 0) {
        fprintf(stderr, "draw rejected: %s\n", nv2a_metal_last_reject());
        return 0;
    }
    return 1;
}

/* THE MICRO-BENCHMARK. A 640x480 target, `draws` full-screen quads per trial
 * with a two-stage, two-texture program, then nv2a_metal_sync -- which waits
 * for the GPU. Wall time per trial, so it includes submission, but the
 * submission is identical in both arms and the pixels are the difference.
 * Reported as the median of the trials. */
static int bench(void)
{
    enum { BW = 640, BH = 480, TRIALS = 15, DRAWS = 64 };
    uint8_t *tgt = calloc(BW * BH, 2), *dep = calloc(BW * BH, 4);
    double t[TRIALS];
    NV2ATextureCopy s;
    D3D8FFCombinerIn in; Case *c;
    ffinit(&in);
    ffstage(&in, 0, D3D8FF_TOP_MODULATE, CUR, TEX, DIF, D3D8FF_TOP_MODULATE, CUR, TEX, DIF);
    ffstage(&in, 1, D3D8FF_TOP_MODULATE2X, CUR, TEX, CUR, D3D8FF_TOP_DISABLE, CUR, TEX, CUR);
    in.texture_bound_mask = 3;
    c = add_ff("bench", &in, 0);
    if (!tgt || !dep) return 1;
    setup(&s, c, BW, BH);
    for (int k = 0; k < TRIALS; ++k) {
        struct timespec a, b;
        clock_gettime(CLOCK_MONOTONIC, &a);
        for (int d = 0; d < DRAWS; ++d)
            if (!draw(&s, tgt, (size_t)BW * BH * 2, dep, (size_t)BW * BH * 4, 0, 0, BW, BH, (unsigned)d)) return 1;
        nv2a_metal_sync();
        clock_gettime(CLOCK_MONOTONIC, &b);
        t[k] = (double)(b.tv_sec - a.tv_sec) * 1e3 + (double)(b.tv_nsec - a.tv_nsec) / 1e6;
    }
    /* Drop the first trial (pipeline compile, texture upload), sort the rest. */
    for (int i = 1; i < TRIALS; ++i)
        for (int j = i + 1; j < TRIALS; ++j)
            if (t[j] < t[i]) { double x = t[i]; t[i] = t[j]; t[j] = x; }
    printf("[BENCH] %d full-screen %dx%d draws per trial: first %.2f ms, median %.2f ms, best %.2f ms"
           " (%.3f ms per draw at the median)\n",
           DRAWS, BW, BH, t[0], t[1 + (TRIALS - 1) / 2], t[1], t[1 + (TRIALS - 1) / 2] / DRAWS);
    nv2a_metal_report();
    free(tgt); free(dep);
    return 0;
}

int main(int argc, char **argv)
{
    FILE *dump;
    int ok = 1, passes = 1;
    make_textures();
    if (argc > 2 && strcmp(argv[2], "vsh") == 0) { use_vsh = 1; build_vsh(); }
    if (argc > 2 && strcmp(argv[2], "bench") == 0) return bench();
    for (int a = 2; a < argc; ++a) if (strcmp(argv[a], "twice") == 0) passes = 2;
    dump = argc > 1 ? fopen(argv[1], "wb") : NULL;
    if (argc > 1 && !dump) { perror(argv[1]); return 1; }
    build_cases();
    for (int pass = 0; pass < passes; ++pass) {
    if (pass) { nv2a_metal_pipelines_settle(); printf("pass 2, after settle:\n"); }
    for (unsigned i = 0; i < ncases; ++i) {
        NV2ATextureCopy s;
        uint32_t h = 2166136261u;
        memset(target, 0x5A, sizeof target);
        memset(depth, 0, sizeof depth);
        nv2a_metal_invalidate(NULL);
        setup(&s, &cases[i], W, H);
        ok &= draw(&s, target, sizeof target, depth, sizeof depth, 0, 0, W, H, i);
        s.blend = 1; s.blend_src = 0x302; s.blend_dst = 0x303;   /* SRC_ALPHA, ONE_MINUS_SRC_ALPHA */
        ok &= draw(&s, target, sizeof target, depth, sizeof depth, 16, 24, 112, 120, i + 3);
        nv2a_metal_sync();
        for (size_t k = 0; k < sizeof target; ++k) { h ^= target[k]; h *= 16777619u; }
        printf("case %2u %-44s cc=%u tmask=%x  fnv=%08x\n", i, cases[i].name, cases[i].cc,
               cases[i].tmask, h);
        if (dump) fwrite(target, 1, sizeof target, dump);
    }
    }
    if (dump) fclose(dump);
    /* Everything queued has finished and the archive is written, so the
     * report's counters are final and a second process finds the shard. */
    nv2a_metal_pipelines_settle();
    nv2a_metal_report();
    return ok ? 0 : 1;
}
