#!/usr/bin/env python3
"""G33a: stage a copy of the gen tree in which every D3D entry point game code
calls is wrapped by a counter. The source tree is never modified.

Each wrapped body is renamed `static void d3d8c_orig_sub_X(void)` and a
wrapper keeps the public name, so every direct call, ABI call and dispatch
table entry reaches the counter first. The wrapper reads the guest return
address the caller pushed and counts the call as GAME or INTERNAL (a D3D
function calling another). It then runs the original body unchanged.

Counting is off unless RECOMP_D3D8_CENSUS=1. With it off the only cost is one
predictable branch per call.

    stage_d3d8_census.py <gen> <dest> --entries experiments/d3d8_boundary/entry_points.json
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil

D3D_LO, D3D_HI = 0x0018CB40, 0x0019A040
SWAP = 0x00198F10

RUNTIME = r'''/* Generated by stage_d3d8_census.py -- counters for the D3D8 boundary census. */
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define D3D8C_N %(n)d
static const uint32_t d3d8c_addr[D3D8C_N] = { %(addrs)s };
static const char *const d3d8c_name[D3D8C_N] = { %(names)s };
/* G34: bytes each entry pops (ret N) from entry_points.json, checked on every
 * call: esp after the original body must be esp at entry + 4 + N, and the
 * callee-saved ebx/esi/edi must come back unchanged (ebp is a C local
 * per generated function, not guest state across a call). That is the contract
 * a replacement body will have to honour; here the originals prove the table. */
static const uint32_t d3d8c_ret[D3D8C_N] = { %(rets)s };
static _Atomic unsigned long long d3d8c_abi_calls, d3d8c_abi_esp_bad[D3D8C_N], d3d8c_abi_reg_bad[D3D8C_N];
static _Atomic uint32_t d3d8c_abi_first_delta[D3D8C_N];
static _Atomic unsigned long long d3d8c_game[D3D8C_N], d3d8c_internal[D3D8C_N];
static _Atomic unsigned long long d3d8c_game_mark[D3D8C_N];
static _Atomic unsigned long long d3d8c_frames;
int g_d3d8_census_on = -1;
static unsigned d3d8c_every = 600;

static void d3d8c_print(const char *why)
{
    unsigned long long frames = atomic_load(&d3d8c_frames);
    fprintf(stderr, "[D3D8-CENSUS] %%s frames=%%llu (per-frame figures are game calls over the last window)\n",
            why, frames);
    for (int i = 0; i < D3D8C_N; ++i) {
        unsigned long long g = atomic_load(&d3d8c_game[i]);
        unsigned long long in = atomic_load(&d3d8c_internal[i]);
        unsigned long long mark = atomic_exchange(&d3d8c_game_mark[i], g);
        if (!g && !in)
            continue;
        fprintf(stderr, "[D3D8-CENSUS] 0x%%08X %%-42s game=%%llu internal=%%llu window_game=%%llu\n",
                d3d8c_addr[i], d3d8c_name[i], g, in, g - mark);
    }
    fflush(stderr);
}

static void d3d8c_abi_print(const char *why)
{
    unsigned long long bad = 0;
    for (int i = 0; i < D3D8C_N; ++i) {
        unsigned long long e = atomic_load(&d3d8c_abi_esp_bad[i]), r = atomic_load(&d3d8c_abi_reg_bad[i]);
        if (!e && !r) continue;
        bad += e + r;
        fprintf(stderr, "[D3D8-ABI] MISMATCH 0x%%08X %%s: esp=%%llu (first delta %%u, table says %%u) callee-saved=%%llu\n",
                d3d8c_addr[i], d3d8c_name[i], e, (unsigned)atomic_load(&d3d8c_abi_first_delta[i]),
                4u + d3d8c_ret[i], r);
    }
    fprintf(stderr, "[D3D8-ABI] %%s calls_checked=%%llu mismatches=%%llu\n", why,
            (unsigned long long)atomic_load(&d3d8c_abi_calls), bad);
    fflush(stderr);
}

void d3d8_census_abi(unsigned idx, uint32_t esp0, uint32_t esp1, const uint32_t before[3], const uint32_t after[3])
{
    if (g_d3d8_census_on <= 0 || idx >= D3D8C_N) return;
    atomic_fetch_add_explicit(&d3d8c_abi_calls, 1, memory_order_relaxed);
    if (esp1 - esp0 != 4u + d3d8c_ret[idx]) {
        uint32_t zero = 0;
        atomic_compare_exchange_strong(&d3d8c_abi_first_delta[idx], &zero, esp1 - esp0);
        atomic_fetch_add_explicit(&d3d8c_abi_esp_bad[idx], 1, memory_order_relaxed);
    }
    if (memcmp(before, after, 3 * sizeof(uint32_t)))
        atomic_fetch_add_explicit(&d3d8c_abi_reg_bad[idx], 1, memory_order_relaxed);
}

static void d3d8c_exit(void) { d3d8c_print("exit"); d3d8c_abi_print("exit"); }

void d3d8_census_hit(unsigned idx, uint32_t ret)
{
    if (g_d3d8_census_on < 0) {
        const char *v = getenv("RECOMP_D3D8_CENSUS");
        const char *e = getenv("RECOMP_D3D8_CENSUS_EVERY");
        g_d3d8_census_on = v && strcmp(v, "1") == 0;
        if (e && atoi(e) > 0)
            d3d8c_every = (unsigned)atoi(e);
        if (g_d3d8_census_on) {
            atexit(d3d8c_exit);
            fprintf(stderr, "[D3D8-CENSUS] armed: %%d entry points, report every %%u swaps\n",
                    D3D8C_N, d3d8c_every);
        }
        if (!g_d3d8_census_on)
            return;
    }
    if (idx >= D3D8C_N)
        return;
    if (ret >= 0x%(lo)08Xu && ret < 0x%(hi)08Xu) {
        atomic_fetch_add_explicit(&d3d8c_internal[idx], 1, memory_order_relaxed);
        return;
    }
    atomic_fetch_add_explicit(&d3d8c_game[idx], 1, memory_order_relaxed);
    if (d3d8c_addr[idx] == 0x%(swap)08Xu) {
        unsigned long long f = atomic_fetch_add(&d3d8c_frames, 1) + 1;
        if (f %% d3d8c_every == 0) {
            d3d8c_print("periodic");
            d3d8c_abi_print("periodic");
        }
    }
}
'''


def body_span(source, name):
    head = "void %s(void)\n{" % name
    start = source.find(head)
    if start < 0 or source.find(head, start + 1) >= 0:
        return None
    end = source.index("\n}\n", start) + 3
    return start, end


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", type=Path)
    ap.add_argument("destination", type=Path)
    ap.add_argument("--entries", type=Path, required=True)
    ap.add_argument("--mirror", action="store_true",
                    help="G39: keep a host mirror of D3D texture bindings and check it against the "
                         "executor after every draw (d3d8_mirror.c); RECOMP_D3D8_MIRROR=1 arms it")
    ap.add_argument("--lift-clear", action="store_true",
                    help="route D3DDevice_Clear through d3d8_lift_clear.h (G37); "
                         "RECOMP_D3D8_LIFT_CLEAR=shadow|1 selects the mode at run time")
    a = ap.parse_args()

    src, dst = a.source.resolve(), a.destination.resolve()
    if dst == src or src in dst.parents:
        raise SystemExit("destination must be separate from the source gen")
    if dst.exists():
        raise SystemExit("destination exists: %s" % dst)
    entries = json.load(open(a.entries))
    files = {p: p.read_text() for p in sorted(src.glob("recomp_*.c"))}

    plan = {}
    for idx, e in enumerate(entries):
        name = "sub_%08X" % int(e["address"], 16)
        found = [(p, body_span(t, name)) for p, t in files.items() if ("void %s(void)\n{" % name) in t]
        if len(found) != 1 or found[0][1] is None:
            raise SystemExit("expected exactly one body for %s, found %d" % (name, len(found)))
        plan[name] = (idx, found[0][0], found[0][1])

    shutil.copytree(src, dst)
    manifest = ["source=%s" % src, "switch=RECOMP_D3D8_CENSUS=1", "entries=%d" % len(entries)]
    by_file = {}
    for name, (idx, path, span) in plan.items():
        by_file.setdefault(path, []).append((span[0], span[1], name, idx))
    for path, items in by_file.items():
        text = files[path]
        wrappers = ["", "/* ---- D3D8 census wrappers (stage_d3d8_census.py) ---- */",
                    "extern int g_d3d8_census_on;",
                    "void d3d8_census_hit(unsigned idx, uint32_t ret);",
                    "void d3d8_census_abi(unsigned idx, uint32_t esp0, uint32_t esp1, const uint32_t before[3], const uint32_t after[3]);"]
        for start, end, name, idx in sorted(items, reverse=True):
            body = text[start:end]
            manifest.append("%s sha256=%s file=%s" % (name, hashlib.sha256(body.encode()).hexdigest(), path.name))
            renamed = body.replace("void %s(void)" % name, "static void d3d8c_orig_%s(void)" % name, 1)
            text = text[:start] + renamed + text[end:]
            body = "d3d8c_orig_%s" % name
            if a.lift_clear and name == "sub_00193830":
                body = "d3d8c_lift_body_%s" % name
                wrappers.append('#include "d3d8_lift_clear.h"')
                wrappers.append("static void %s(void) { if (d3d8_lift_clear_mode()) d3d8_lift_clear();"
                                " else d3d8c_orig_%s(); }" % (body, name))
                manifest.append("lift: %s -> d3d8_lift_clear.h" % name)
            if a.mirror and name in ("sub_0018F6C0", "sub_0018F760"):
                hooked = "d3d8c_hooked_%s" % name
                fn = "d3d8m_zenable" if name == "sub_0018F6C0" else "d3d8m_stencilenable"
                wrappers.append("void %s(uint32_t v);" % fn)
                wrappers.append("static void %s(void) { uint32_t v = MEM32(esp + 4u); %s(); %s(v); }" % (hooked, body, fn))
                body = hooked
                manifest.append("mirror: %s (%s)" % (name, fn))
            if a.mirror and name == "sub_001905F0":
                hooked = "d3d8c_hooked_%s" % name
                wrappers.append("void d3d8m_vs_constant(uint32_t reg, uint32_t data, uint32_t count);")
                wrappers.append("static void %s(void) { uint32_t r = MEM32(esp + 4u), d = MEM32(esp + 8u), n = MEM32(esp + 12u);"
                                " %s(); d3d8m_vs_constant(r, d, n); }" % (hooked, body))
                body = hooked
                manifest.append("mirror: %s (vertex constants)" % name)
            if a.mirror and name == "sub_00199BE0":
                hooked = "d3d8c_hooked_%s" % name
                wrappers.append("void d3d8m_set_pixel_shader(uint32_t handle);")
                wrappers.append("static void %s(void) { uint32_t h = MEM32(esp + 4u); %s(); d3d8m_set_pixel_shader(h); }" % (hooked, body))
                body = hooked
                manifest.append("mirror: %s (pixel shader)" % name)
            if a.mirror and name == "sub_0018CC60":
                hooked = "d3d8c_hooked_%s" % name
                wrappers.append("void d3d8m_set_transform(uint32_t state, uint32_t pm);")
                wrappers.append("static void %s(void) { uint32_t st = MEM32(esp + 4u), pm = MEM32(esp + 8u); %s(); d3d8m_set_transform(st, pm); }" % (hooked, body))
                body = hooked
                manifest.append("mirror: %s (transforms)" % name)
            if a.mirror and name in ("sub_001900D0", "sub_0018E090"):
                # G41 cross-check hooks. SetStreamSource(StreamNumber,
                # pStreamData, Stride) ret 0xC; SetIndices(pIndexData,
                # BaseVertexIndex) ret 8.
                hooked = "d3d8c_hooked_%s" % name
                if name == "sub_001900D0":
                    wrappers.append("void d3d8m_set_stream_source(uint32_t stream, uint32_t vb, uint32_t stride);")
                    wrappers.append("static void %s(void) { uint32_t s = MEM32(esp + 4u), vb = MEM32(esp + 8u),"
                                    " st = MEM32(esp + 12u); %s(); d3d8m_set_stream_source(s, vb, st); }" % (hooked, body))
                else:
                    wrappers.append("void d3d8m_set_indices(uint32_t ib, uint32_t base);")
                    wrappers.append("static void %s(void) { uint32_t ib = MEM32(esp + 4u), b = MEM32(esp + 8u);"
                                    " %s(); d3d8m_set_indices(ib, b); }" % (hooked, body))
                body = hooked
                manifest.append("mirror: %s (streams/indices)" % name)
            if a.mirror and name == "sub_0018E930":
                hooked = "d3d8c_hooked_%s" % name
                wrappers.append("void d3d8m_simple(uint32_t hdr, uint32_t value);")
                wrappers.append("static void %s(void) { uint32_t h = ecx, v = edx; %s(); d3d8m_simple(h, v); }" % (hooked, body))
                body = hooked
                manifest.append("mirror: %s (render state)" % name)
            if a.mirror and name in ("sub_0018DF10", "sub_001993A0", "sub_00199300"):
                hooked = "d3d8c_hooked_%s" % name
                wrappers.append("void d3d8m_set_texture(uint32_t stage, uint32_t tex);"
                                " void d3d8m_after_draw(uint32_t kind, uint32_t a1, uint32_t a2, uint32_t a3);")
                if name == "sub_0018DF10":
                    wrappers.append("static void %s(void) { uint32_t st = MEM32(esp + 4u), tx = MEM32(esp + 8u);"
                                    " %s(); d3d8m_set_texture(st, tx); }" % (hooked, body))
                else:
                    # G41: the draw's three stdcall arguments, read before the
                    # original pops them. DrawIndexedVertices (kind 2) takes
                    # (prim, count, pIndexData); DrawVertices (kind 1) (prim, start, count).
                    kind = 2 if name == "sub_001993A0" else 1
                    wrappers.append("static void %s(void) { uint32_t a1 = MEM32(esp + 4u), a2 = MEM32(esp + 8u),"
                                    " a3 = MEM32(esp + 12u); %s(); d3d8m_after_draw(%du, a1, a2, a3); }" % (hooked, body, kind))
                body = hooked
                manifest.append("mirror: %s" % name)
            wrappers.append(
                "void %s(void) { if (!g_d3d8_census_on) { %s(); return; }"
                " d3d8_census_hit(%du, MEM32(esp)); if (g_d3d8_census_on <= 0) { %s(); return; }"
                " uint32_t e0 = esp, b0[3] = { ebx, esi, edi }; %s();"
                " uint32_t b1[3] = { ebx, esi, edi }; d3d8_census_abi(%du, e0, esp, b0, b1); }"
                % (name, body, idx, body, body, idx))
        # the renamed statics must be declared before any earlier use in this file
        decls = "\n".join("static void d3d8c_orig_%s(void);" % n for _, _, n, _ in items)
        first = min(s for s, _, _, _ in items)
        text = text[:first] + decls + "\n" + text[first:] + "\n".join(wrappers) + "\n"
        (dst / path.name).write_text(text)

    if a.mirror:
        # G43: two INTERNAL D3D functions, not entry points, so they are
        # wrapped here and not through the census table. Both are called only
        # from the lazy flusher 0x1964A0 (dirty bits 0x800 and 0x2000); the
        # hook runs BEFORE the original and records the inputs it is about to
        # read, so the check can transcribe exactly what D3D last emitted.
        for name, fn in (("sub_00197F90", "d3d8m_ff_builder_entry"),    # combiner builder
                         ("sub_00195610", "d3d8m_fog_entry")):           # fog / final combiner
            if name in plan:
                raise SystemExit("%s is also a census entry; hook it through the entry path" % name)
            found = [p for p in sorted(dst.glob("recomp_*.c")) if ("void %s(void)\n{" % name) in p.read_text()]
            if len(found) != 1:
                raise SystemExit("expected exactly one body for %s, found %d" % (name, len(found)))
            text = found[0].read_text()
            span = body_span(text, name)
            if span is None:
                raise SystemExit("could not delimit %s" % name)
            body = text[span[0]:span[1]]
            manifest.append("%s sha256=%s file=%s" % (name, hashlib.sha256(body.encode()).hexdigest(), found[0].name))
            renamed = body.replace("void %s(void)" % name, "static void d3d8m_orig_%s(void)" % name, 1)
            text = text[:span[0]] + renamed + text[span[1]:]
            text += ("\n/* ---- G43 mirror hook (stage_d3d8_census.py) ---- */\n"
                     "void %s(void);\n"
                     "void %s(void) { %s(); d3d8m_orig_%s(); }\n" % (fn, name, fn, name))
            found[0].write_text(text)
            manifest.append("mirror: %s (G43, %s before the original)" % (name, fn))

    names = [(e["name"] or "sub_%08X" % int(e["address"], 16)).split(" (")[0].replace('"', "'") for e in entries]
    (dst / "recomp_zz_d3d8_census.c").write_text(RUNTIME % dict(
        n=len(entries),
        addrs=", ".join("0x%08Xu" % int(e["address"], 16) for e in entries),
        names=", ".join('"%s"' % n for n in names),
        lo=D3D_LO, hi=D3D_HI, swap=SWAP,
        rets=", ".join("%du" % (e["ret_bytes"][0] if e["ret_bytes"] else 0) for e in entries)))
    if a.lift_clear:
        shutil.copyfile(Path(__file__).with_name("d3d8_lift_clear.h"), dst / "d3d8_lift_clear.h")
    if a.mirror:
        shutil.copyfile(Path(__file__).with_name("d3d8_mirror.c"), dst / "recomp_zz_d3d8_mirror.c")
    (dst / "D3D8_CENSUS_MANIFEST.txt").write_text("\n".join(manifest) + "\n")
    print("staged %d wrappers in %d files -> %s" % (len(plan), len(by_file), dst))


if __name__ == "__main__":
    main()
