#!/usr/bin/env python3
"""G33a: stage a copy of the gen tree in which every D3D entry point game code
calls is wrapped by a counter. The source tree is never modified.

Each wrapped body is renamed `static void d3d8c_orig_sub_X(void)` and a
wrapper keeps the public name, so every direct call, ABI call and dispatch
table entry reaches the counter first. The wrapper reads the guest return
address the caller pushed and counts the call as GAME or INTERNAL (a D3D
function calling another). It then runs the original body unchanged.

Counting is off unless RECOMP_D3D8_CENSUS=1. With it off the only cost is one
predictable branch per call.

    stage_d3d8_census.py <gen> <dest> --entries experiments/d3d8_boundary/entry_points.json
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil

D3D_LO, D3D_HI = 0x0018CB40, 0x0019A040
SWAP = 0x00198F10

RUNTIME = r'''/* Generated by stage_d3d8_census.py -- counters for the D3D8 boundary census. */
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define D3D8C_N %(n)d
static const uint32_t d3d8c_addr[D3D8C_N] = { %(addrs)s };
static const char *const d3d8c_name[D3D8C_N] = { %(names)s };
static _Atomic unsigned long long d3d8c_game[D3D8C_N], d3d8c_internal[D3D8C_N];
static _Atomic unsigned long long d3d8c_game_mark[D3D8C_N];
static _Atomic unsigned long long d3d8c_frames;
int g_d3d8_census_on = -1;
static unsigned d3d8c_every = 600;

static void d3d8c_print(const char *why)
{
    unsigned long long frames = atomic_load(&d3d8c_frames);
    fprintf(stderr, "[D3D8-CENSUS] %%s frames=%%llu (per-frame figures are game calls over the last window)\n",
            why, frames);
    for (int i = 0; i < D3D8C_N; ++i) {
        unsigned long long g = atomic_load(&d3d8c_game[i]);
        unsigned long long in = atomic_load(&d3d8c_internal[i]);
        unsigned long long mark = atomic_exchange(&d3d8c_game_mark[i], g);
        if (!g && !in)
            continue;
        fprintf(stderr, "[D3D8-CENSUS] 0x%%08X %%-42s game=%%llu internal=%%llu window_game=%%llu\n",
                d3d8c_addr[i], d3d8c_name[i], g, in, g - mark);
    }
    fflush(stderr);
}

static void d3d8c_exit(void) { d3d8c_print("exit"); }

void d3d8_census_hit(unsigned idx, uint32_t ret)
{
    if (g_d3d8_census_on < 0) {
        const char *v = getenv("RECOMP_D3D8_CENSUS");
        const char *e = getenv("RECOMP_D3D8_CENSUS_EVERY");
        g_d3d8_census_on = v && strcmp(v, "1") == 0;
        if (e && atoi(e) > 0)
            d3d8c_every = (unsigned)atoi(e);
        if (g_d3d8_census_on) {
            atexit(d3d8c_exit);
            fprintf(stderr, "[D3D8-CENSUS] armed: %%d entry points, report every %%u swaps\n",
                    D3D8C_N, d3d8c_every);
        }
        if (!g_d3d8_census_on)
            return;
    }
    if (idx >= D3D8C_N)
        return;
    if (ret >= 0x%(lo)08Xu && ret < 0x%(hi)08Xu) {
        atomic_fetch_add_explicit(&d3d8c_internal[idx], 1, memory_order_relaxed);
        return;
    }
    atomic_fetch_add_explicit(&d3d8c_game[idx], 1, memory_order_relaxed);
    if (d3d8c_addr[idx] == 0x%(swap)08Xu) {
        unsigned long long f = atomic_fetch_add(&d3d8c_frames, 1) + 1;
        if (f %% d3d8c_every == 0)
            d3d8c_print("periodic");
    }
}
'''


def body_span(source, name):
    head = "void %s(void)\n{" % name
    start = source.find(head)
    if start < 0 or source.find(head, start + 1) >= 0:
        return None
    end = source.index("\n}\n", start) + 3
    return start, end


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", type=Path)
    ap.add_argument("destination", type=Path)
    ap.add_argument("--entries", type=Path, required=True)
    a = ap.parse_args()

    src, dst = a.source.resolve(), a.destination.resolve()
    if dst == src or src in dst.parents:
        raise SystemExit("destination must be separate from the source gen")
    if dst.exists():
        raise SystemExit("destination exists: %s" % dst)
    entries = json.load(open(a.entries))
    files = {p: p.read_text() for p in sorted(src.glob("recomp_*.c"))}

    plan = {}
    for idx, e in enumerate(entries):
        name = "sub_%08X" % int(e["address"], 16)
        found = [(p, body_span(t, name)) for p, t in files.items() if ("void %s(void)\n{" % name) in t]
        if len(found) != 1 or found[0][1] is None:
            raise SystemExit("expected exactly one body for %s, found %d" % (name, len(found)))
        plan[name] = (idx, found[0][0], found[0][1])

    shutil.copytree(src, dst)
    manifest = ["source=%s" % src, "switch=RECOMP_D3D8_CENSUS=1", "entries=%d" % len(entries)]
    by_file = {}
    for name, (idx, path, span) in plan.items():
        by_file.setdefault(path, []).append((span[0], span[1], name, idx))
    for path, items in by_file.items():
        text = files[path]
        wrappers = ["", "/* ---- D3D8 census wrappers (stage_d3d8_census.py) ---- */",
                    "extern int g_d3d8_census_on;",
                    "void d3d8_census_hit(unsigned idx, uint32_t ret);"]
        for start, end, name, idx in sorted(items, reverse=True):
            body = text[start:end]
            manifest.append("%s sha256=%s file=%s" % (name, hashlib.sha256(body.encode()).hexdigest(), path.name))
            renamed = body.replace("void %s(void)" % name, "static void d3d8c_orig_%s(void)" % name, 1)
            text = text[:start] + renamed + text[end:]
            wrappers.append("void %s(void) { if (g_d3d8_census_on) d3d8_census_hit(%du, MEM32(esp)); d3d8c_orig_%s(); }"
                            % (name, idx, name))
        # the renamed statics must be declared before any earlier use in this file
        decls = "\n".join("static void d3d8c_orig_%s(void);" % n for _, _, n, _ in items)
        first = min(s for s, _, _, _ in items)
        text = text[:first] + decls + "\n" + text[first:] + "\n".join(wrappers) + "\n"
        (dst / path.name).write_text(text)

    names = [(e["name"] or "sub_%08X" % int(e["address"], 16)).split(" (")[0].replace('"', "'") for e in entries]
    (dst / "recomp_zz_d3d8_census.c").write_text(RUNTIME % dict(
        n=len(entries),
        addrs=", ".join("0x%08Xu" % int(e["address"], 16) for e in entries),
        names=", ".join('"%s"' % n for n in names),
        lo=D3D_LO, hi=D3D_HI, swap=SWAP))
    (dst / "D3D8_CENSUS_MANIFEST.txt").write_text("\n".join(manifest) + "\n")
    print("staged %d wrappers in %d files -> %s" % (len(plan), len(by_file), dst))


if __name__ == "__main__":
    main()
