#!/usr/bin/env python3
"""DSOUND lift, step 1: stage a copy of the gen tree in which every DSOUND
entry point game code calls is wrapped by a counter, an ABI check and, for the
calls that shape the host design, an argument log. The source tree is never
modified. The D3D counterpart is stage_d3d8_census.py; the mechanism is the
same: the original body is renamed `static void dsc_orig_sub_X(void)` and a
wrapper keeps the public name, so every direct call, ABI call and dispatch
table entry reaches the wrapper first.

RECOMP_DSOUND_CENSUS=1 arms it. Off, the cost is one predictable branch.
RECOMP_DSOUND_CENSUS_EVERY=<seconds> sets the report period (default 30).

    stage_dsound_census.py <gen> <dest> --entries experiments/dsound_boundary/entry_points.json
"""
import argparse, hashlib, json, re, shutil
from pathlib import Path

DS_LO, DS_HI = 0x0019E340, 0x001BA8A0

# Argument logging: name -> (number of stack args to capture, post-call hook).
# Captured before the original runs (the callee pops them), logged after it
# returns, so out-parameters and eax are visible.
LOGGED = {
    "IDirectSound_CreateSoundBuffer": 4,
    "IDirectSoundBuffer_SetBufferData": 3,
    "IDirectSoundBuffer_Play": 4,
    "IDirectSoundBuffer_Stop": 1,
    "IDirectSoundBuffer_Lock": 8,
    "IDirectSoundBuffer_Unlock": 5,
    "IDirectSoundBuffer_SetLoopRegion": 3,
    "IDirectSoundBuffer_SetCurrentPosition": 2,
    "IDirectSoundBuffer_GetCurrentPosition": 3,
    "IDirectSoundBuffer_GetStatus": 2,
    "IDirectSoundBuffer_SetFrequency": 2,
    "IDirectSoundBuffer_SetVolume": 2,
    "IDirectSoundBuffer_SetHeadroom": 2,
    "IDirectSoundBuffer_SetMixBins": 2,
    "IDirectSoundBuffer_Release": 1,
    "DirectSoundCreate": 3,
    "IDirectSound_DownloadEffectsImage": 5,
}

RUNTIME = r'''/* Generated by stage_dsound_census.py -- the DSOUND boundary census. */
#define RECOMP_GENERATED_CODE
#include "recomp_funcs.h"
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define DSC_N %(n)d
static const uint32_t dsc_addr[DSC_N] = { %(addrs)s };
static const char *const dsc_name[DSC_N] = { %(names)s };
static const uint32_t dsc_ret[DSC_N] = { %(rets)s };
static _Atomic unsigned long long dsc_game[DSC_N], dsc_internal[DSC_N], dsc_mark[DSC_N];
static _Atomic unsigned long long dsc_abi_calls, dsc_esp_bad[DSC_N], dsc_reg_bad[DSC_N];
static _Atomic uint32_t dsc_first_delta[DSC_N];
static _Atomic unsigned dsc_logged[DSC_N];
int g_dsound_census_on = -1;
static unsigned dsc_every = 30, dsc_log_cap = 400;
static _Atomic long long dsc_next_report;

static double dsc_now(void)
{
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec * 1e-9;
}
static double dsc_t0;

static void dsc_print(const char *why)
{
    unsigned long long bad = 0;
    fprintf(stderr, "[DSOUND-CENSUS] %%s t=%%.1f (window = since the last report)\n", why, dsc_now() - dsc_t0);
    for (int i = 0; i < DSC_N; ++i) {
        unsigned long long g = atomic_load(&dsc_game[i]), in = atomic_load(&dsc_internal[i]);
        unsigned long long m = atomic_exchange(&dsc_mark[i], g);
        unsigned long long e = atomic_load(&dsc_esp_bad[i]), r = atomic_load(&dsc_reg_bad[i]);
        bad += e + r;
        if (!g && !in) continue;
        fprintf(stderr, "[DSOUND-CENSUS] 0x%%08X %%-40s game=%%llu internal=%%llu window_game=%%llu%%s\n",
                dsc_addr[i], dsc_name[i], g, in, g - m, (e || r) ? "  <-- ABI MISMATCH" : "");
        if (e || r)
            fprintf(stderr, "[DSOUND-ABI] MISMATCH 0x%%08X %%s: esp=%%llu (first delta %%u, table %%u) callee-saved=%%llu\n",
                    dsc_addr[i], dsc_name[i], e, (unsigned)atomic_load(&dsc_first_delta[i]), 4u + dsc_ret[i], r);
    }
    fprintf(stderr, "[DSOUND-ABI] %%s calls_checked=%%llu mismatches=%%llu\n", why,
            (unsigned long long)atomic_load(&dsc_abi_calls), bad);
    fflush(stderr);
}
static void dsc_exit(void) { dsc_print("exit"); }

int dsc_arm(void)
{
    if (g_dsound_census_on < 0) {
        const char *v = getenv("RECOMP_DSOUND_CENSUS");
        const char *e = getenv("RECOMP_DSOUND_CENSUS_EVERY");
        const char *c = getenv("RECOMP_DSOUND_CENSUS_LOG_CAP");
        if (e && atoi(e) > 0) dsc_every = (unsigned)atoi(e);
        if (c && atoi(c) >= 0) dsc_log_cap = (unsigned)atoi(c);
        dsc_t0 = dsc_now();
        atomic_store(&dsc_next_report, (long long)dsc_every);
        g_dsound_census_on = v && strcmp(v, "1") == 0;
        if (g_dsound_census_on) {
            atexit(dsc_exit);
            fprintf(stderr, "[DSOUND-CENSUS] armed: %%d entry points, report every %%u s, log cap %%u per entry\n",
                    DSC_N, dsc_every, dsc_log_cap);
        }
    }
    return g_dsound_census_on;
}

void dsound_census_hit(unsigned idx, uint32_t ret)
{
    if (idx >= DSC_N) return;
    if (ret >= 0x%(lo)08Xu && ret < 0x%(hi)08Xu) { atomic_fetch_add(&dsc_internal[idx], 1); return; }
    atomic_fetch_add(&dsc_game[idx], 1);
    long long due = atomic_load(&dsc_next_report);
    if (dsc_now() - dsc_t0 >= (double)due &&
        atomic_compare_exchange_strong(&dsc_next_report, &due, due + (long long)dsc_every))
        dsc_print("periodic");
}

void dsound_census_abi(unsigned idx, uint32_t esp0, uint32_t esp1, const uint32_t b[3], const uint32_t a[3])
{
    if (idx >= DSC_N) return;
    atomic_fetch_add(&dsc_abi_calls, 1);
    if (esp1 - esp0 != 4u + dsc_ret[idx]) {
        uint32_t z = 0; atomic_compare_exchange_strong(&dsc_first_delta[idx], &z, esp1 - esp0);
        atomic_fetch_add(&dsc_esp_bad[idx], 1);
    }
    if (memcmp(b, a, 3 * sizeof(uint32_t))) atomic_fetch_add(&dsc_reg_bad[idx], 1);
}

/* The argument log. `a` is the caller's pushed arguments (a[0] = first), `r`
 * is eax after the original returned. Only guest memory reads; nothing the
 * title sees changes. */
static uint32_t rd32(uint32_t va) { return va ? MEM32(va) : 0u; }
static uint16_t rd16(uint32_t va) { return va ? MEM16(va) : 0u; }
void dsound_census_log(unsigned idx, const char *name, const uint32_t *a, unsigned n, uint32_t r, uint32_t ret_va)
{
    if (idx >= DSC_N || atomic_fetch_add(&dsc_logged[idx], 1) >= dsc_log_cap) return;
    char extra[256] = "";
    if (!strcmp(name, "IDirectSound_CreateSoundBuffer")) {
        uint32_t d = a[1], wf = rd32(d + 12u);
        snprintf(extra, sizeof extra,
                 " desc{size=%%u flags=%%08X bytes=%%u wfx=%%08X mixbins=%%08X inbin=%%u}"
                 " wfx{tag=%%u ch=%%u rate=%%u bits=%%u align=%%u} -> buf=%%08X",
                 rd32(d), rd32(d + 4u), rd32(d + 8u), wf, rd32(d + 16u), rd32(d + 20u),
                 rd16(wf), rd16(wf + 2u), rd32(wf + 4u), rd16(wf + 14u), rd16(wf + 12u), rd32(a[2]));
    } else if (!strcmp(name, "IDirectSoundBuffer_Lock")) {
        snprintf(extra, sizeof extra, " -> p1=%%08X n1=%%u p2=%%08X n2=%%u",
                 rd32(a[3]), rd32(a[4]), rd32(a[5]), rd32(a[6]));
    } else if (!strcmp(name, "IDirectSoundBuffer_GetCurrentPosition")) {
        snprintf(extra, sizeof extra, " -> play=%%u write=%%u", rd32(a[1]), rd32(a[2]));
    } else if (!strcmp(name, "IDirectSoundBuffer_GetStatus")) {
        snprintf(extra, sizeof extra, " -> status=%%08X", rd32(a[1]));
    } else if (!strcmp(name, "DirectSoundCreate")) {
        snprintf(extra, sizeof extra, " -> ds=%%08X", rd32(a[1]));
    }
    char args[160] = ""; size_t o = 0;
    for (unsigned i = 0; i < n && o < sizeof args - 12; ++i)
        o += (size_t)snprintf(args + o, sizeof args - o, "%%s%%08X", i ? " " : "", a[i]);
    fprintf(stderr, "[DSOUND-CALL] t=%%.3f %%s(%%s) = %%08X from %%08X%%s\n",
            dsc_now() - dsc_t0, name, args, r, ret_va, extra);
}
'''

def body_span(source, name):
    head = "void %s(void)\n{" % name
    start = source.find(head)
    if start < 0 or source.find(head, start + 1) >= 0:
        return None
    return start, source.index("\n}\n", start) + 3

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", type=Path)
    ap.add_argument("destination", type=Path)
    ap.add_argument("--entries", type=Path, required=True)
    ap.add_argument("--shadow", action="store_true",
                    help="G48 phase 3: replay every logged call into the host model (dsound_shadow.c) and "
                         "compare its GetStatus/GetCurrentPosition with DSOUND's; RECOMP_DSOUND_SHADOW=1 arms it")
    a = ap.parse_args()
    src, dst = a.source.resolve(), a.destination.resolve()
    if dst == src or src in dst.parents:
        raise SystemExit("destination must be separate from the source gen")
    if dst.exists():
        raise SystemExit("destination exists: %s" % dst)
    entries = json.load(open(a.entries))
    files = {p: p.read_text() for p in sorted(src.glob("recomp_*.c"))}
    plan = {}
    for idx, e in enumerate(entries):
        name = "sub_%08X" % int(e["address"], 16)
        found = [(p, body_span(t, name)) for p, t in files.items() if ("void %s(void)\n{" % name) in t]
        if len(found) != 1 or found[0][1] is None:
            raise SystemExit("expected exactly one body for %s, found %d" % (name, len(found)))
        plan[name] = (idx, e, found[0][0], found[0][1])
    shutil.copytree(src, dst)
    manifest = ["source=%s" % src, "switch=RECOMP_DSOUND_CENSUS=1", "entries=%d" % len(entries)]
    by_file = {}
    for name, (idx, e, path, span) in plan.items():
        by_file.setdefault(path, []).append((span[0], span[1], name, idx, e))
    for path, items in by_file.items():
        text = files[path]
        wrappers = ["", "/* ---- DSOUND census wrappers (stage_dsound_census.py) ---- */",
                    "extern int g_dsound_census_on; int dsc_arm(void);",
                    "void dsound_census_hit(unsigned idx, uint32_t ret);",
                    "void dsound_census_abi(unsigned idx, uint32_t esp0, uint32_t esp1, const uint32_t b[3], const uint32_t a[3]);",
                    "void dsound_census_log(unsigned idx, const char *name, const uint32_t *a, unsigned n, uint32_t r, uint32_t ret_va);",
                    "void dss_after(const char *name, const uint32_t *a, uint32_t eax);"]
        for start, end, name, idx, e in sorted(items, key=lambda t: -t[0]):
            body = text[start:end]
            manifest.append("%s sha256=%s file=%s" % (name, hashlib.sha256(body.encode()).hexdigest(), path.name))
            text = text[:start] + body.replace("void %s(void)" % name, "static void dsc_orig_%s(void)" % name, 1) + text[end:]
            nargs = LOGGED.get(e["name"], 0)
            cap = ""
            log = ""
            if nargs:
                cap = " uint32_t ar[%d]; for (unsigned k = 0; k < %du; ++k) ar[k] = MEM32(esp + 4u + 4u * k);" % (nargs, nargs)
                log = ' dsound_census_log(%du, "%s", ar, %du, eax, ra);' % (idx, e["name"], nargs)
                if a.shadow:
                    log += ' dss_after("%s", ar, eax);' % e["name"]
            wrappers.append(
                "void %s(void) { if (!g_dsound_census_on || (g_dsound_census_on < 0 && !dsc_arm())) { dsc_orig_%s(); return; }"
                " uint32_t ra = MEM32(esp); dsound_census_hit(%du, ra);%s"
                " uint32_t e0 = esp, b0[3] = { ebx, esi, edi }; dsc_orig_%s();"
                " uint32_t b1[3] = { ebx, esi, edi }; dsound_census_abi(%du, e0, esp, b0, b1);%s }"
                % (name, name, idx, cap, name, idx, log))
        decls = "\n".join("static void dsc_orig_%s(void);" % n for _, _, n, _, _ in items)
        first = min(s for s, _, _, _, _ in items)
        text = text[:first] + decls + "\n" + text[first:] + "\n".join(wrappers) + "\n"
        (dst / path.name).write_text(text)
    rets = []
    for e in entries:
        r = e.get("ret_bytes") or [0]
        rets.append(r[0] if len(r) == 1 else 0xFFFF)   # ambiguous: every call will read as a mismatch, and say so
    (dst / "recomp_zz_dsound_census.c").write_text(RUNTIME % dict(
        n=len(entries),
        addrs=", ".join("0x%08Xu" % int(e["address"], 16) for e in entries),
        names=", ".join('"%s"' % e["name"] for e in entries),
        rets=", ".join("%du" % r for r in rets), lo=DS_LO, hi=DS_HI))
    if a.shadow:
        shutil.copyfile(Path(__file__).with_name("dsound_shadow.c"), dst / "recomp_zz_dsound_shadow.c")
        manifest.append("shadow: recomp_zz_dsound_shadow.c (RECOMP_DSOUND_SHADOW=1)")
    (dst / "DSOUND_CENSUS_MANIFEST.txt").write_text("\n".join(manifest) + "\n")
    print("staged %d wrappers in %d files -> %s" % (len(plan), len(by_file), dst))

if __name__ == "__main__":
    main()
